[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[project]
name = "ssh-snakehole"
version = "0.1.0"
description = "Temporary, code-paired SSH as a Python library"
requires-python = ">=3.12.14,<3.15"
dependencies = ["wsproto==1.3.2", "h11==0.16.0"]
license = "MIT"
readme = "README.txt"

[project.scripts]
ssh-snakehole = "ssh_snakehole.cli:main"

[tool.setuptools.packages.find]
include = ["ssh_snakehole*"]

[tool.setuptools.package-data]
ssh_snakehole = ["*.json", "licenses/*"]
